version: "3.9"
services:
  sd:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ../sd-data:/data
      - ../sd-output:/output
      - sd-cache:/root/.cache
      - ./:/ciclo-limite
    environment:
      - APP_MAIN_FILE=ciclo_limite.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto_config/:/mosquitto/config/
      - ./mosquitto_log/:/mosquitto/log/
      # - mosquitto_data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
volumes:
  sd-cache:
